import bcrypt from 'bcryptjs';

// Pre-hashed default password for all demo accounts: 'Password123!'
const DEMO_PASSWORD_HASH = bcrypt.hashSync('Password123!', 10);

export const store = {
  users: [
    {
      _id: 'usr_customer_1',
      name: 'Arjun Mehta',
      email: 'arjun.mehta@example.com',
      phone: '+1 (416) 555-0192',
      country: 'Canada',
      role: 'CUSTOMER',
      passwordHash: DEMO_PASSWORD_HASH,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      _id: 'usr_patient_1',
      name: 'Sunita Mehta',
      email: 'sunita.mehta@example.com',
      phone: '+91 98721 00123',
      country: 'India',
      role: 'PATIENT',
      passwordHash: DEMO_PASSWORD_HASH,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    },
    {
      _id: 'usr_rep_1',
      name: 'Rahul Sharma',
      email: 'rahul.sharma@example.com',
      phone: '+91 98140 55432',
      country: 'India',
      role: 'REPRESENTATIVE',
      passwordHash: DEMO_PASSWORD_HASH,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    },
    {
      _id: 'usr_admin_1',
      name: 'ApnoCare Admin',
      email: 'admin@apnocare.local',
      phone: '+91 1800 2766 227',
      country: 'India',
      role: 'ADMIN',
      passwordHash: DEMO_PASSWORD_HASH,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    },
  ],

  patients: [
    {
      _id: 'pat_1',
      customerId: 'usr_customer_1',
      name: 'Sunita Mehta',
      relationship: 'Mother',
      age: 68,
      gender: 'Female',
      phone: '+91 98721 00123',
      address: 'House 42, Model Town, Near Geeta Mandir',
      city: 'Jalandhar',
      state: 'Punjab',
      pincode: '144003',
      bloodGroup: 'B+',
      mobility: 'Independent with slow walking',
      primaryDoctor: 'Dr. Harvinder Singh (Cardiology)',
      emergencyContactName: 'Dr. Rajesh Khanna (Family Physician)',
      emergencyContactPhone: '+91 98150 99881',
      currentMedications: [
        { name: 'Telmisartan 40mg', frequency: 'Once daily (Morning)', purpose: 'Blood Pressure' },
        { name: 'Metformin 500mg', frequency: 'Twice daily (After meals)', purpose: 'Type 2 Diabetes' },
        { name: 'Calcium + Vit D3', frequency: 'Once daily (Post lunch)', purpose: 'Bone Health' },
      ],
      createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    },
    {
      _id: 'pat_2',
      customerId: 'usr_customer_1',
      name: 'Baldev Mehta',
      relationship: 'Father',
      age: 72,
      gender: 'Male',
      phone: '+91 98721 00124',
      address: 'House 42, Model Town, Near Geeta Mandir',
      city: 'Jalandhar',
      state: 'Punjab',
      pincode: '144003',
      bloodGroup: 'O+',
      mobility: 'Uses walking cane',
      primaryDoctor: 'Dr. Surinder Vohra (Orthopedics)',
      emergencyContactName: 'Sunita Mehta',
      emergencyContactPhone: '+91 98721 00123',
      currentMedications: [
        { name: 'Glucosamine Sulfate 1500mg', frequency: 'Once daily', purpose: 'Knee Joint Support' },
      ],
      createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    },
  ],

  representatives: [
    {
      _id: 'rep_1',
      userId: 'usr_rep_1',
      name: 'Rahul Sharma',
      phone: '+91 98140 55432',
      email: 'rahul.sharma@example.com',
      city: 'Jalandhar',
      state: 'Punjab',
      photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      badgeId: 'AC-JAL-042',
      verificationStatus: 'VERIFIED',
      policeVerificationStatus: 'PASSED',
      trainingCompleted: true,
      experienceYears: 4,
      rating: 4.9,
      totalAssists: 148,
      activeAssists: 1,
      skills: ['Elderly Escort', 'Hospital Navigation', 'Post-Op Assistance', 'Emergency First Response'],
      languages: ['English', 'Hindi', 'Punjabi'],
      emergencyContact: '+91 98140 00001',
    },
    {
      _id: 'rep_2',
      userId: 'usr_rep_2',
      name: 'Priya Patel',
      phone: '+91 98250 11223',
      email: 'priya.patel@example.com',
      city: 'Chandigarh',
      state: 'Punjab / Chandigarh',
      photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      badgeId: 'AC-CHD-019',
      verificationStatus: 'VERIFIED',
      policeVerificationStatus: 'PASSED',
      trainingCompleted: true,
      experienceYears: 3,
      rating: 4.8,
      totalAssists: 86,
      activeAssists: 0,
      skills: ['Diagnostic Escort', 'Prescription Collection', 'Wheelchair Assistance'],
      languages: ['English', 'Hindi', 'Punjabi'],
      emergencyContact: '+91 98250 00000',
    },
    {
      _id: 'rep_3',
      userId: 'usr_rep_3',
      name: 'Aman Deep Singh',
      phone: '+91 98141 77665',
      email: 'amandeep@example.com',
      city: 'Ludhiana',
      state: 'Punjab',
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      badgeId: 'AC-LDH-008',
      verificationStatus: 'UNDER_REVIEW',
      policeVerificationStatus: 'PENDING',
      trainingCompleted: true,
      experienceYears: 2,
      rating: 4.7,
      totalAssists: 12,
      activeAssists: 0,
      skills: ['Hospital Registration', 'Doctor Liaison'],
      languages: ['English', 'Punjabi'],
      emergencyContact: '+91 98141 00000',
    },
  ],

  serviceRequests: [
    {
      _id: 'req_101',
      customerId: 'usr_customer_1',
      patientId: 'pat_1',
      patientName: 'Sunita Mehta',
      representativeId: 'rep_1',
      representativeName: 'Rahul Sharma',
      serviceType: 'Diagnostic Tests',
      category: 'Ultrasound & Fasting Blood Panel',
      description: 'Accompany mom to Apex Diagnostic Centre for scheduled Abdominal Ultrasound and collect printout copies.',
      status: 'SCHEDULED',
      priority: 'NORMAL',
      city: 'Jalandhar',
      scheduledDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
      scheduledTime: '10:30 AM',
      partnerProvider: 'Apex Diagnostic Centre, Civil Lines',
      estimatedPriceINR: 1200,
      paymentStatus: 'PAID',
      timeline: [
        {
          status: 'REQUEST_CREATED',
          title: 'Request Created by Arjun',
          note: 'Assistance booked from Toronto, Canada.',
          timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
        },
        {
          status: 'ASSIGNED',
          title: 'Care Representative Assigned',
          note: 'Rahul Sharma (Badge AC-JAL-042, 4.9⭐) assigned to Sunita Mehta.',
          timestamp: new Date(Date.now() - 10 * 3600000).toISOString(),
        },
        {
          status: 'PATIENT_CONTACTED',
          title: 'Mom Contacted via Phone',
          note: 'Rahul spoke with Sunita ji to reconfirm 10-hour fasting requirements for test.',
          timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
        },
        {
          status: 'SCHEDULED',
          title: 'Slot Confirmed with Apex Diagnostic',
          note: 'Confirmed appointment #APX-4912 for tomorrow 10:30 AM.',
          timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
        },
      ],
      documents: [
        {
          name: 'Doctor_Ultrasound_Prescription.pdf',
          url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&auto=format&fit=crop&q=80',
          type: 'Prescription',
          uploadedAt: new Date(Date.now() - 11 * 3600000).toISOString(),
        },
      ],
      createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    },
    {
      _id: 'req_102',
      customerId: 'usr_customer_1',
      patientId: 'pat_2',
      patientName: 'Baldev Mehta',
      representativeId: 'rep_1',
      representativeName: 'Rahul Sharma',
      serviceType: 'Medicine Assistance',
      category: 'Prescription Refill Collection',
      description: 'Pick up monthly refill of knee joint medicine and Telmisartan from Apollo Pharmacy with bill.',
      status: 'COMPLETED',
      priority: 'NORMAL',
      city: 'Jalandhar',
      scheduledDate: new Date(Date.now() - 4 * 86400000).toISOString().split('T')[0],
      scheduledTime: '04:00 PM',
      partnerProvider: 'Apollo Pharmacy, Model Town',
      estimatedPriceINR: 650,
      paymentStatus: 'PAID',
      timeline: [
        {
          status: 'REQUEST_CREATED',
          title: 'Request Created',
          note: 'Medicine collection requested by Arjun.',
          timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
        },
        {
          status: 'ARRIVED',
          title: 'Representative at Pharmacy',
          note: 'Prescription verified and invoice generated.',
          timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
        },
        {
          status: 'DOCUMENTS_UPLOADED',
          title: 'Pharmacy Bill & Batch Photo Uploaded',
          note: 'Verified expiry date is 2028.',
          timestamp: new Date(Date.now() - 4 * 86400000 + 3600000).toISOString(),
        },
        {
          status: 'COMPLETED',
          title: 'Delivered to Home',
          note: 'Handed over directly to Baldev ji. Signed delivery acknowledgment.',
          timestamp: new Date(Date.now() - 4 * 86400000 + 7200000).toISOString(),
        },
      ],
      documents: [
        {
          name: 'Pharmacy_Invoice_Receipt.pdf',
          url: 'https://images.unsplash.com/photo-1554415707-9e4966779435?w=800&auto=format&fit=crop&q=80',
          type: 'Receipt',
          uploadedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
        },
      ],
      createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    },
  ],

  healthRecords: [
    {
      _id: 'rec_1',
      patientId: 'pat_1',
      patientName: 'Sunita Mehta',
      title: 'Echo & Cardiac Stress Report',
      category: 'Cardiology',
      documentType: 'Diagnostic Report',
      doctorName: 'Dr. Harvinder Singh',
      facility: 'Tagore Heart Hospital, Jalandhar',
      date: '2026-08-15',
      fileUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
      notes: 'Normal sinus rhythm, LVEF 60%. Next review scheduled in 6 months.',
      uploadedBy: 'Rahul Sharma (Rep)',
      createdAt: '2026-08-15T11:30:00.000Z',
    },
    {
      _id: 'rec_2',
      patientId: 'pat_1',
      patientName: 'Sunita Mehta',
      title: 'Annual Blood Sugar & HbA1c Panel',
      category: 'Endocrinology',
      documentType: 'Lab Test',
      doctorName: 'Dr. Rajesh Khanna',
      facility: 'Dr. Lal PathLabs, Model Town',
      date: '2026-07-22',
      fileUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
      notes: 'HbA1c: 6.8% (Well managed). Fasting sugar: 114 mg/dL.',
      uploadedBy: 'Arjun Mehta (Customer)',
      createdAt: '2026-07-22T09:15:00.000Z',
    },
    {
      _id: 'rec_3',
      patientId: 'pat_2',
      patientName: 'Baldev Mehta',
      title: 'Bilateral Knee Joint X-Ray (Standing)',
      category: 'Orthopedics',
      documentType: 'Radiology / X-Ray',
      doctorName: 'Dr. Surinder Vohra',
      facility: 'Patel Hospital, Jalandhar',
      date: '2026-06-10',
      fileUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?w=800&auto=format&fit=crop&q=80',
      notes: 'Grade II Osteoarthritis changes in medial compartment. Advised in-home physiotherapy.',
      uploadedBy: 'Rahul Sharma (Rep)',
      createdAt: '2026-06-10T14:45:00.000Z',
    },
  ],

  partners: [
    {
      _id: 'part_1',
      name: 'Patel Multi-Speciality Hospital',
      type: 'Hospital',
      city: 'Jalandhar',
      address: 'Civil Lines, Near BMC Chowk',
      phone: '+91 181 508 8888',
      website: 'https://patelhospital.demo',
      verified: true,
      services: ['24/7 Emergency', 'Cardiology', 'Orthopedics', 'ICU Accompaniment'],
      rating: 4.8,
    },
    {
      _id: 'part_2',
      name: 'Apex Diagnostic & Imaging Centre',
      type: 'Diagnostic Center',
      city: 'Jalandhar',
      address: 'Mall Road, Opposite Company Bagh',
      phone: '+91 181 223 4455',
      website: 'https://apexdiagnostic.demo',
      verified: true,
      services: ['MRI 3T', 'CT Scan', 'Ultrasound Color Doppler', 'Pathology'],
      rating: 4.9,
    },
    {
      _id: 'part_3',
      name: 'Apollo Pharmacy 24/7',
      type: 'Pharmacy',
      city: 'Jalandhar',
      address: 'Model Town Market, Near Geeta Mandir',
      phone: '+91 181 462 1200',
      website: 'https://apollopharmacy.demo',
      verified: true,
      services: ['Prescription Fulfillment', 'Cold-Chain Insulin Storage', 'Home Delivery'],
      rating: 4.7,
    },
    {
      _id: 'part_4',
      name: 'Fortis Hospital Mohali',
      type: 'Hospital',
      city: 'Chandigarh / Mohali',
      address: 'Sector 62, Phase VIII',
      phone: '+91 172 502 1222',
      website: 'https://fortismohali.demo',
      verified: true,
      services: ['Tertiary Care', 'Oncology', 'Neurology', 'Organ Transplant Support'],
      rating: 4.9,
    },
  ],

  serviceAreas: [
    { city: 'Jalandhar', state: 'Punjab', status: 'ACTIVE', activeReps: 8, totalRequests: 320 },
    { city: 'Ludhiana', state: 'Punjab', status: 'ACTIVE', activeReps: 6, totalRequests: 245 },
    { city: 'Amritsar', state: 'Punjab', status: 'ACTIVE', activeReps: 5, totalRequests: 190 },
    { city: 'Chandigarh / Mohali / Panchkula', state: 'UT / Punjab / Haryana', status: 'ACTIVE', activeReps: 12, totalRequests: 480 },
    { city: 'Delhi NCR (Gurugram / Noida)', state: 'Delhi NCR', status: 'ACTIVE', activeReps: 22, totalRequests: 810 },
    { city: 'Bengaluru', state: 'Karnataka', status: 'ACTIVE', activeReps: 18, totalRequests: 620 },
  ],

  waitlist: [
    {
      _id: 'wl_1',
      name: 'Rohan Deshmukh',
      email: 'rohan.d@example.com',
      phone: '+1 408 555 9210',
      patientCity: 'Pune',
      state: 'Maharashtra',
      neededService: 'Elderly Home Care & Doctor Escort',
      createdAt: '2026-09-08T10:00:00.000Z',
    },
    {
      _id: 'wl_2',
      name: 'Ananya Roy',
      email: 'ananya.roy@example.com',
      phone: '+44 7700 900123',
      patientCity: 'Kolkata',
      state: 'West Bengal',
      neededService: 'Post-Surgery Hospital Discharge Assistance',
      createdAt: '2026-09-10T15:20:00.000Z',
    },
  ],

  familyShares: [
    {
      _id: 'share_1',
      customerId: 'usr_customer_1',
      patientId: 'pat_1',
      invitedEmail: 'simran.mehta@example.com',
      invitedName: 'Simran Mehta (Sister in Vancouver)',
      permission: 'FULL_ACCESS',
      status: 'ACCEPTED',
      createdAt: '2026-08-20T10:00:00.000Z',
    },
  ],

  subscriptions: [
    {
      _id: 'sub_1',
      customerId: 'usr_customer_1',
      planId: 'plan_care',
      planName: 'Care Plan',
      status: 'ACTIVE',
      billingCycle: 'Monthly',
      priceINR: 4999,
      priceUSD: 59,
      startDate: '2026-08-01',
      renewalDate: '2026-10-01',
      featuresIncluded: [
        'Dedicated Care Coordinator',
        '2 Free Doctor Accompaniments / month',
        'Unlimited Medicine Pickup Coordination',
        'Emergency SOS Protocol Support',
        'Secure Cloud Health Record Vault',
      ],
    },
  ],

  notifications: [
    {
      _id: 'notif_1',
      userId: 'usr_customer_1',
      title: 'Appointment Scheduled at Apex Diagnostic',
      message: 'Care Representative Rahul Sharma confirmed 10:30 AM slot for your mother Sunita Mehta.',
      type: 'SCHEDULED',
      read: false,
      createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
    {
      _id: 'notif_2',
      userId: 'usr_customer_1',
      title: 'Monthly Telmisartan Delivered',
      message: 'Rahul Sharma delivered medicines to your father Baldev Mehta with pharmacy receipt attached.',
      type: 'COMPLETED',
      read: true,
      createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    },
    {
      _id: 'notif_3',
      userId: 'usr_rep_1',
      title: 'Upcoming Visit Reminder',
      message: 'Ultrasound accompaniment tomorrow at 10:30 AM for Sunita Mehta (House 42, Model Town).',
      type: 'REMINDER',
      read: false,
      createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
  ],

  auditLogs: [
    {
      _id: 'log_1',
      actorId: 'usr_admin_1',
      actorName: 'ApnoCare Admin',
      action: 'REPRESENTATIVE_VERIFIED',
      target: 'Rahul Sharma (AC-JAL-042)',
      details: 'Police verification cleared and badge issued.',
      timestamp: '2026-07-10T10:14:00.000Z',
    },
    {
      _id: 'log_2',
      actorId: 'usr_customer_1',
      actorName: 'Arjun Mehta',
      action: 'FAMILY_ACCESS_GRANTED',
      target: 'simran.mehta@example.com',
      details: 'Granted Full Access to Sunita Mehta medical profile.',
      timestamp: '2026-08-20T10:00:00.000Z',
    },
    {
      _id: 'log_3',
      actorId: 'usr_rep_1',
      actorName: 'Rahul Sharma',
      action: 'DOCUMENT_UPLOADED',
      target: 'Pharmacy_Invoice_Receipt.pdf',
      details: 'Uploaded receipt for request #req_102.',
      timestamp: '2026-09-07T16:10:00.000Z',
    },
  ],
};
